# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BeatFace' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BeatFace
pod 'CVCalendar', '~> 1.6.1'
pod 'SwiftLocation', '~> 3.2.1'
pod 'SVProgressHUD'
pod 'Alamofire'
pod 'SwiftyPickerPopover'
 pod 'Cloudinary'
pod 'GooglePlaces'
pod 'SDWebImage', '~> 4.0'
pod 'BraintreeDropIn'

end
